### ISSUE TITLE
Sonarcloud?

### ISSUE THREAD

**Issue by AldaronLau** [ardaku/arc#17]
@CATboardBETA you said we can't use it, right?  If so, I guess it should removed.

**Comment by CATboardBETA** [comment]
Correct. We might be able to set up some stuff with CI to communicate with SonarQube on our server, but idk. More research req.

**Comment by AldaronLau** [comment]
Re-opening because if we're not using it, we should remove it from the repo before closing:

https://github.com/ardaku/quantii/blob/stable/.github/workflows/build.yml
