### ISSUE TITLE
gh-pages design doc

### ISSUE THREAD

**Issue by hyperswine** [ardaku/arc#19]
I think we should make a gh-pages for quantii. I have a sample `gh-pages` branch with mdbooks and a CI to deploy to pages.
We could use it for writing design documentation and etc.

rn i dont think pages is enabled for this repo. Or at least `GH_TOKEN` does not allow it

**Comment by AldaronLau** [comment]
I enabled gh-pages for https://ardaku.org/quantii/, but idk if that fixes the issue.

Also, thinking maybe it should be it's own repo called quantii-docs?  What do you think?

**Comment by hyperswine** [comment]
Yeah that seemed to fix it.

If you can setup a quantii-docs repo with all of the stuff in `main`, then I guess it would be nice. Since we're publishing it to https://ardaku.org/quantii anyway
